name: Run unit tests
#github uses only in main workflows ?
on:
  workflow_run:
    workflows: ["Build"]
    branches: ["develop"]
    types: ["completed"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore depndencies
      run: dotnet restore
    - name: Build code
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test HouseRentingSystem.UnitTests/HouseRentingSystem.UnitTests.csproj --no-build --verbosity normal
